# Generated by Django 4.0 on 2022-01-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Closed', 'CLOSED'), ('Frosen', 'FROZEN')], default='Active', max_length=6),
        ),
    ]
